import { GoogleGenAI } from '@google/genai';

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { question, jobDetails, candidateInfo, projectContext } = req.body || {};

    if (!question || typeof question !== 'string' || !question.trim()) {
      return res.status(400).json({ error: 'A coach question is required.' });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(500).json({ error: 'GEMINI_API_KEY is not configured in Vercel.' });
    }

    const ai = new GoogleGenAI({ apiKey });
    const prompt = `You are helping a job candidate prepare a concise interview answer.

Use the information below to craft a strong response to the coach's question.

JOB DETAILS:
${jobDetails?.trim() || 'No job description provided.'}

CANDIDATE BACKGROUND / RESUME:
${candidateInfo?.trim() || 'No resume background provided.'}

PROJECT CONTEXT:
${projectContext?.trim() || 'No uploaded project context provided.'}

COACH QUESTION:
${question.trim()}

Instructions:
- Answer as the candidate, not as the coach.
- Keep the response practical, confident, and interview-ready.
- Reference the candidate's background and uploaded project evidence when relevant.
- If a detail is missing, do not invent major facts. Keep it honest and structured.
- Prefer 2-4 concise paragraphs or a 3-part structured response if appropriate.
- Do not mention that these are generated by AI.
- Keep the final answer easy to say out loud in an interview.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });

    const text = typeof response.text === 'string' ? response.text : '';
    return res.status(200).json({
      answer: text.trim() || 'I can speak to my background and project work here, including the problem I was solving, the trade-offs I considered, and the outcome I delivered.'
    });
  } catch (error: any) {
    console.error('[suggest-answer]', error?.message ?? error);
    return res.status(502).json({
      error: 'Unable to generate a suggested answer right now.'
    });
  }
}
